[package]
name = "gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.100"
env_logger = "0.11.8"
serde = { version = "1.0.228", features = ["derive"] }
awc = "3.8.1"